adding branch protection rules (#113)
Co-authored-by: Mohammed <114924143+MohammedSZN@users.noreply.github.com>

diff --git a/.github/workflows/synapseDeploy.yml b/.github/workflows/synapseDeploy.yml
--- a/.github/workflows/synapseDeploy.yml
+++ b/.github/workflows/synapseDeploy.yml
@@ -12,6 +12,21 @@ on:
       - scripts/synapse/**
 
 jobs:
+# check_branch - branch protection rules for uat and prd | init - passes env variable
+  check_branch:
+    runs-on: ubuntu-latest
+    steps:
+      - name: if 'main' branch then only allow 'uat' to merge
+        if: github.base_ref == 'main' && github.head_ref != 'uat'
+        run: |
+          echo "ERROR: You can only merge into main from uat."
+          exit 1
+      - name: if 'uat' branch then only allow 'dev' to merge 
+        if: github.base_ref == 'uat' && github.head_ref != 'dev'
+        run: |
+          echo "ERROR: You can only merge into uat from dev."
+          exit 1
+  
   init:
     runs-on: ubuntu-latest
     outputs:
